version: '2'

services:
  user-accounts-postgres-prod:
    image: postgres:${USER_ACCOUNTS_POSTGRES_VERSION}
    container_name: user-accounts-postgres-prod
    restart: always
    environment:
      - POSTGRES_DB=user-accounts
      - POSTGRES_USER=${USER_ACCOUNTS_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${USER_ACCOUNTS_POSTGRES_PASSWORD}
    networks:
      - user-accounts-network-prod
    ports:
      - '5401:5432'
    volumes:
      - user-accounts-postgres-volume-prod:/var/lib/postgresql/data

volumes:
  user-accounts-postgres-volume-prod:
    driver: local

networks:
  user-accounts-network-prod:
    driver: bridge